### ISSUE TITLE
readPandas() header check throwing error

### ISSUE THREAD

**Issue by terraswat** [ucscHexmap/hexagram#65] opened 2018-04-08 01:51 UTC
Verana was looking for why her data file was throwing errors and it turned out to be our header-checking code in utils.py:readPandas(). She says:

 I tried to change the read_csv command inside the readPandas function:
- I included 'low_memory=False' -> did not work, ran out of memory
- I included 'dtype=float' -> did not work, the first line is text
- I changed the header option to 'header=0' and commented out the code following that checks for a header -> worked! 

Interesting that the low_memory flag seemed to do the opposite of what it should.

**Comment by terraswat** [comment] 2018-04-09 15:08
This was on a file with what appears to have a proper header:

/data/data/featureSpace/Treehouse/THPED_July2017/treehouse_public_samples_unique_hugo
_log2_tpm_plus_1_expr_var_filtered.2017-08-11.tsv

**Comment by mrJeppard** [comment] 2018-04-10 00:27
Closing due to inability to reproduce the error using the compute environment on hexcalc.

**Closed by mrJeppard** 2018-04-10 00:27 UTC
Labels: -bug, data server
